import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Rukn Al Dyafa | Hospitality Services",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        {/* Google Analytics script */}
        <script
            async
            src={`https://www.googletagmanager.com/gtag/js?id=G-YWDFCK5NPF`} // Replace with your GA4 ID
          ></script>
          <script
            dangerouslySetInnerHTML={{
              __html: `
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());

                gtag('config', 'YOUR_MEASUREMENT_ID'); // Replace with your GA4 ID
              `,
            }}
          ></script>
        <link rel="icon" href="/favicon.ico" />
        {/* You can also add other meta tags or stylesheets here */}
      </head>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
